steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/tarnapi/document-qa-service:latest', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tarnapi/document-qa-service:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google-cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'document-qa-service'
    - '--image'
    - 'gcr.io/tarnapi/document-qa-service:latest'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '2'
    - '--set-env-vars'
    - 'PROJECT_ID=tarnapi'
    - '--timeout'
    - '300s'

images: ['gcr.io/tarnapi/document-qa-service:latest']
logsBucket: 'gs://poliseeai-cloudbuild-logs' # Add this line



